### PR TITLE
fix-getDataBaseByUrl时如果jdbc url的参数中有/如Asia/Shanghai会解析失败

### PR DESCRIPTION
**Pull request by geosmart**
fix-getDataBaseByUrl时如果jdbc url的参数中有/如Asia/Shanghai会解析失败

测试
```java
    @Test
    public void getDataBaseByUrl() {
        String url1 =
                "jdbc:mysql://127.0.0.1:3306/flinkx?serverTimezone=Asia/Shanghai&characterEncoding=utf8";
        String db = BinlogUtil.getDataBaseByUrl(url1);
        assertEquals("flinkx", db);

        String url2 =
                "jdbc:mysql://10.199.142.48:3306/flinkx?LocalInfile=false&allowUrlInLocalInfile=false";
        String db2 = BinlogUtil.getDataBaseByUrl(url2);
        assertEquals("flinkx", db2);

        String url3 = "jdbc:mysql://10.199.142.48:3306/flinkx";
        String db3 = BinlogUtil.getDataBaseByUrl(url3);
        assertEquals("flinkx", db3);

        String url4 = "jdbc:mysql://10.199.142.48:3306/flinkx?";
        String db4 = BinlogUtil.getDataBaseByUrl(url4);
        assertEquals("flinkx", db4);
    }
```

### CODE REVIEW

**Comment by FlechazoW** [comment]
I create a new issue(#1110) for this pr, please check it whether i describe clear?

**Comment by geosmart** [comment]
why licence check error? I doesn't   change  dependency

**Comment by FlechazoW** [comment]
> why licence check error? I doesn't change dependency

Ignore it.

**Comment by FlechazoW** [comment]
PR has been cherry pick.

**Pull request closed without merging**
