### PR TITLE
[hotfix-#899][conf] fix config check error

### PR DESCRIPTION
**Pull request by huyuanfeng2018**
issues :  https://github.com/DTStack/chunjun/issues/899

### CODE REVIEW

**Comment by FlechazoW** [comment]
Ok. I will merge it, but before that, can you edit the commit message according to the template [hotfix-#issueID][fix-module] fix-commit. @huyuanfeng2018

**Comment by huyuanfeng2018** [comment]
> Ok. I will merge it, but before that, can you edit the commit message according to the template [hotfix-#issueID][fix-module] fix-commit. @huyuanfeng2018

ok I will edit

**Comment by FlechazoW** [comment]
Hey bro, you should change the commit message of this pr, not the title.

image

**Comment by FlechazoW** [comment]
@huyuanfeng2018

**Comment by huyuanfeng2018** [comment]
> @huyuanfeng2018

i got it

**Pull request merged**
