### PR TITLE
[hotfix-#1853] [connector jdbc] jdbc toInternal methods should process data by field name rather than index #1853

### PR DESCRIPTION
**Pull request by david-gao1**
## Which issue you fix
Fixes # (issue).

## Checklist:

- [ ] I have executed the **'mvn spotless:apply'** command to format my code.
- [ ] I have a meaningful commit message (including the issue id, **the template of commit message is '[label-type-#issue-id][fixed-module] a meaningful commit message.'**)
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have checked my code and corrected any misspellings.
- [ ] My commit is only one. (If there are multiple commits, you can use 'git squash' to compress multiple commits into one.)

### CODE REVIEW

**Comment by zoudaokoulife** [comment]
代码上看是合理的，不过涉及到核心功能的改动。我们本地先验证下数据同步 相关逻辑是否有影响之后再合并

**Comment by david-gao1** [comment]
好的



---Original---
From: ***@***.***&gt;
Date: Thu, Dec 14, 2023 19:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DTStack/chunjun] [hotfix-#1853] [connector jdbc] jdbc toInternalmethods should process data by field name rather than index #1853 (PR #1854)




 
代码上看是合理的，不过涉及到核心功能的改动。我们本地先验证下数据同步 相关逻辑是否有影响之后再合并

**Comment by zoudaokoulife** [comment]
@david-gao1 
从上下文结构上看，问题的根本原因是在 构建SupportsProjectionPushDown 的情况下，使用了剪枝导致的。
上面提供的方式是能解决问题。但是从结构上看通过在查询的时候 使用剪枝后的column 会更合适，减少了查询的column 。
建议在com.dtstack.chunjun.connector.jdbc.source.JdbcDynamicTableSource#getScanRuntimeProvider 调整 columns 的构造逻辑。
`final RowType rowType = (RowType) physicalRowDataType.getLogicalType();
        TypeInformation<RowData> typeInformation = InternalTypeInfo.of(rowType);
        ResolvedSchema projectionSchema =
                ResolvedSchema.physical(rowType.getFieldNames(), physicalRowDataType.getChildren())
List<Column> columns = projectionSchema.getColumns()
`
你这边是否能更新一个版本呢？

**Comment by david-gao1** [comment]
好的 感谢提醒 我研究下



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 18, 2023 10:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DTStack/chunjun] [hotfix-#1853] [connector jdbc] jdbc toInternalmethods should process data by field name rather than index #1853 (PR #1854)




 
@david-gao1
 从上下文结构上看，问题的根本原因是在 构建SupportsProjectionPushDown 的情况下，使用了剪枝导致的。
 上面提供的方式是能解决问题。但是从结构上看通过在查询的时候 使用剪枝后的column 会更合适，减少了查询的column 。
 建议在com.dtstack.chunjun.connector.jdbc.source.JdbcDynamicTableSource#getScanRuntimeProvider 调整 columns 的构造逻辑。
 final RowType rowType = (RowType) physicalRowDataType.getLogicalType(); TypeInformation<RowData&gt; typeInformation = InternalTypeInfo.of(rowType); ResolvedSchema projectionSchema = ResolvedSchema.physical(rowType.getFieldNames(), physicalRowDataType.getChildren()) List<Column&gt; columns = projectionSchema.getColumns() 
 你这边是否能更新一个版本呢？

**Pull request closed without merging**
