### PR TITLE
add oceanbasecdc connector

### LINKED ISSUE #702: [Feature] Add OceanBase Plugin for ChunJun
OceanBase Database is a native distributed relational database. It is developed entirely by Alibaba and Ant Group. OceanBase Database is built on a common server cluster. Based on the Paxos protocol and its distributed structure, OceanBase Database provides high availability and linear scalability. OceanBase Database is not dependent on specific hardware architectures.
Same as pulsar, we need connector of oceabase.

### PR DESCRIPTION
**Pull request by whhe**
## Purpose of this pull request

Add OceanBase CDC connector.

## Which issue you fix
Close #702.

Note that there are still some work to do:
1. Implement `OceanBaseCdcColumnConverter.createInternalConverter`. The type of log message is not in one-to-one correspondence with the type of flink, so we can't run the json sync task without `column` and `transformer` for now.
2. Resolve `protobuf-java` version conflicts. The `oblogclient` used in OceanBase CDC connector depends on `protobuf-java-3.18.2`, while other packages depend on `protobuf-java-2.5.0`, so we can only test the connector using shell (with stream connector) but not in the local-test module (with all connectors) for now.
3. Add more tests for all types conversion.

I think these issues can be resolved later, and I would love to contribute for it.

## Checklist:

- [x] I have executed the **'mvn spotless:apply'** command to format my code.
- [ ]  I have a meaningful commit message (including the issue id, **the template of commit message is '[label-type-#issue-id][fixed-module] a meaningful commit message.'**)
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] I have checked my code and corrected any misspellings.
- [x] My commit is only one. (If there are multiple commits, you can use 'git squash' to compress multiple commits into one.)

### CODE REVIEW

**Review by FlechazoW — COMMENTED** [review]
Please add apache license.

**Comment by ll076110** [comment]
Thank you for the PR, I think there is no problem with the merge, can you provide a usage document?

**Comment by whhe** [comment]
> Thank you for the PR, I think there is no problem with the merge, can you provide a usage document?

Should I append the doc in this pr or provide it in a new one?

**Comment by FlechazoW** [comment]
> > Thank you for the PR, I think there is no problem with the merge, can you provide a usage document?
> 
> Should I append the doc in this pr or provide it in a new one?

I think it would be better to add the documentation to this pr.

**Comment by whhe** [comment]
> > > Thank you for the PR, I think there is no problem with the merge, can you provide a usage document?
> > 
> > 
> > Should I append the doc in this pr or provide it in a new one?
> 
> I think it would be better to add the documentation to this pr.

Doc added.

**Pull request merged**
