### PR TITLE
fix[#764] Duplicate data occurred when use jdbc polling Data

### PR DESCRIPTION
**Pull request by huyongze**
修复问题：JDBC数据源在实时扫表拉取数据时，在数据量大于1万条时，会出现部分数据重复，后续在增加数据，便不会出现重复。
原因：在实时抽取数据过程中，第一次从JDBC数据源的SQL，没有按照splitKey进行排序，导致获取的下一次的起始位置数据不是上一次轮询后的最大值，导致数据重复。
修复方式：在扫表时对更新SQL，增加order by，避免该问题的发生
根据反馈：将代码合并到Master分支

### CODE REVIEW

**Comment by FlechazoW** [comment]
Thanks! But i think you should rebase 'master' branch of DTstack/chunjun into your own branch with command 'git rebase master', because your branch is behind the master branch.

**Comment by huyongze** [comment]
I'm Sorry ,this is my first time to commit code. Could i update code in my 'master' branch and commit push

**Comment by FlechazoW** [comment]
> 

That's ok, don't be worry, i will help you to finish this pr.

**Comment by huyongze** [comment]
I have to commit from my 'master' bench ,should i close this comment

**Comment by FlechazoW** [comment]
OK. I will review it.

**Pull request closed without merging**
