### PR TITLE
[hotfix-#1799][connector][jdbc] Fix related issues when the write mode is replace/update

### LINKED ISSUE #1799: [Bug] [connector][jdbc] 当写入模式是replace/update时相关问题
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

sql模式，测试向mysql写入时，当配置写入模式时，出现相关问题：
1、没有相关参数可以配置写入模式，
2、当在sql create table sink里，配置了主键 PRIMARY KEY (xxx) NOT ENFORCED 不生效问题，原因是获取到错误的主键列名
3、当在 sql create table sink里，不配置主键 PRIMARY KEY 时，setKeyRowType、setKeyRowConverter 未正确执行，导致空指针。
4、另一个小问题，也可能是我测试用例不太好。比如一张表有两个唯一索引 username 、email , 现在两条记录，如图， 
image

但是通过chunjun sql 再向表里插入一条 username 在id=1里，email在id=2里重复数据 在chunjun里就会报错 脏数据，

image

image

如果是使用 mysql sql（REPLACE INTO flinkx_write_mode(id,username,email)
VALUES(1,'aa-replace-11', 'bb@126.com'); ）语法插入的话，虽然能插入成功，但是数据会容易混乱。两条数据就剩下一条了。以下是插入后结果

image

对只有一列是主键（唯一索引）开发测试没啥问题，但是当有两个唯一索引的时候，插入的新数据涉及到两行时就会报脏数据错误

### What you expected to happen

--

### How to reproduce

创建 mysql 表
```
CREATE TABLE flinkx_test.flinkx_write_mode (
  id int(11) NOT NULL,
  username varchar(255) NOT NULL DEFAULT '',
  email varchar(50) NOT NULL DEFAULT ''
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

ALTER TABLE flinkx_test.flinkx_write_mode
ADD UNIQUE INDEX UK_flinkx_write_mode_email (email);

ALTER TABLE flinkx_test.flinkx_write_mode
ADD UNIQUE INDEX UK_flinkx_write_mode_username (username);

```

插入数据：

```
INSERT INTO flinkx_write_mode (id, username, email) VALUES
(1, 'aa-replace-11', 'aa@163.com'),
(2, 'bb', 'bb@126.com');
```

```

CREATE TABLE source
(
    `username` varchar,
    `email` varchar
) WITH (
      'connector' = 'stream-x',
      'number-of-rows' = '1' 
      );
CREATE TABLE sink
(
    id int,
    `username` varchar,
    `email` varchar
    ,PRIMARY KEY (id) NOT ENFORCED
--     ,PRIMARY KEY (username, email) NOT ENFORCED
) WITH (
      'password' = 'xxx',
      'connector' = 'mysql-x',
      'sink.buffer-flush.interval' = '1000',
      'sink.buffer-flush.max-rows' = '1024',
      'sink.all-replace' = 'false',
      'write-mode' = 'replace',
      'table-name' = 'flinkx_write_mode',
      'url' = 'jdbc:mysql://xxxx:3306/flinkx_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&connectTimeout=3000&zeroDateTimeBehavior=convertToNull&useunicode=true&characterEncoding=utf8&useSSL=false&useCursorFetch=true&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull',
      'username' = 'xxx'
      );

CREATE TEMPORARY VIEW source_1 AS
select * FROM (VALUES (1,'aa', 'bb@126.com'))  AS t (id, username, email)
;

insert into sink select * from source_1;



```

### Anything else

_No response_

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by libailin**
…

## Which issue you fix
Fixes #1799 

## Checklist:

- [] I have executed the **'mvn spotless:apply'** command to format my code.
- [] I have a meaningful commit message (including the issue id, **the template of commit message is '[label-type-#issue-id][fixed-module] a meaningful commit message.'**)
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have checked my code and corrected any misspellings.
- [ ] My commit is only one. (If there are multiple commits, you can use 'git squash' to compress multiple commits into one.)

### CODE REVIEW

**Comment by Paddy0523** [comment]
@libailin

**Comment by Paddy0523** [comment]
image

**Comment by libailin** [comment]
看到你回复的非常详细，我仔细想了想，如果截图这段去掉的话，
8ea65985f25eab2e1dd414d6a807de32
那么sql 模式下，就必须要在 create table时声明 PRIMARY KEY ，这样是不是不太方便。json模式是可以自动获取的。
我有个两个想法，麻烦指教下。
1、能否把我新加的写入模式 WRITE_MODE 改成 sql模式下自动获取主键（索引）的开关配置，默认关闭，打开的时候再执行自动获取逻辑
2、保持原来逻辑，从pr里去掉新增的 写入模式  和 自动获取主键（索引）相关代码。必须要用户手动声明主键字段。

经过讨论 采用 第2种

**Comment by Paddy0523** [comment]
主要是为了让插件的行为和SQL语义保持一致

**Review by Paddy0523 — APPROVED** [review]
LGTM

**Comment by Paddy0523** [comment]
LGTM

**Pull request merged**
